name: Carwash

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout our repository
      uses: actions/checkout@v4

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          pwd
          ls
          cd /home/ubuntu/carwash
          git pull origin main
          sudo docker compose -f docker-compose.yml down --rmi all
          sudo docker compose -f docker-compose.yml up -d
          sudo docker compose -f docker-compose.yml up -d
          sudo docker compose -f docker-compose.yml up -d
          